FROM golang:1.23

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod ./
RUN go mod download && go mod verify

COPY . .
RUN go build -race -v -o /usr/local/bin/app ./cmd/rplb

EXPOSE 8000
EXPOSE 8080

ENV RPLB_F=
ENV RPLB_B=
ENV RPLB_A=sticky

CMD ["sh", "-c", "app -f \"${RPLB_F}\" -b \"${RPLB_B}\" -a \"${RPLB_A}\""]
