FROM golang:1.23

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod ./
RUN go mod download && go mod verify

COPY . .
RUN go build -race -v -o /usr/local/bin/app ./cmd/rplb

EXPOSE 8000
EXPOSE 8080

ENV FE=
ENV BE=
ENV ALGO=sticky

CMD ["sh", "-c", "app -f \"${FE}\" -b \"${BE}\" -a \"${ALGO}\""]
