name: Go Build Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: |
          docker compose -f example/compose.yaml up -d rplb
          curl http://localhost:8080
          curl http://localhost:8000/metrics
        # run: go test ./...